import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Lora } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/utils/context/authContext";
import ModalProvider from "@/utils/context/modalContext";
import { Slide, ToastContainer } from "react-toastify";
import IceCreamProvider from "@/utils/context/iceCreamContext";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});
export const metadata: Metadata = {
  title: "Scoopies Ice cream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${lora.variable} antialiased`}
      >
        <Suspense fallback={<p>Loading...</p>}>
          <AuthProvider>
            <ModalProvider>
              <ToastContainer
                position='top-right'
                autoClose={2000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme='colored'
                transition={Slide}
              />{" "}
              <IceCreamProvider>{children}</IceCreamProvider>
            </ModalProvider>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
